In [1]:
import pandas as pd
weather = pd.read_csv("WeatherNY.csv", index_col="DATE")
weather

,STATION,NAME,AWND,PRCP,TAVG,TMAX,TMIN,WESD
DATE,,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31,0.0
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37,0.0
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46,0.0
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47,0.0
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28,0.0
...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,NaN
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,NaN
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,NaN
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,NaN
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",NaN,0.00,64.0,74,56,NaN

In [2]:
null_pct = weather.apply(pd.isnull).sum()/weather.shape[0]
null_pct

STATION    0.000000
NAME       0.000000
AWND       0.003438
PRCP       0.000000
TAVG       0.310823
TMAX       0.000000
TMIN       0.000000
WESD       0.554447
dtype: float64

In [3]:
weather.apply(pd.isnull).sum()

STATION       0
NAME          0
AWND         31
PRCP          0
TAVG       2803
TMAX          0
TMIN          0
WESD       5000
dtype: int64

In [5]:
valid_columns = weather.columns[null_pct < 0.5]
valid_columns

Index(['STATION', 'NAME', 'AWND', 'PRCP', 'TAVG', 'TMAX', 'TMIN'], dtype='object')

In [6]:
weather = weather[valid_columns].copy()
weather

,STATION,NAME,AWND,PRCP,TAVG,TMAX,TMIN
DATE,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28
...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",NaN,0.00,64.0,74,56

In [7]:
weather.columns = weather.columns.str.lower()
weather

,station,name,awnd,prcp,tavg,tmax,tmin
DATE,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28
...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",NaN,0.00,64.0,74,56

In [8]:
weather = weather.ffill()
weather.apply(pd.isnull).sum()

station    0
name       0
awnd       0
prcp       0
tavg       0
tmax       0
tmin       0
dtype: int64

In [11]:

# Select only the numeric columns for calculating IQR
numeric_cols = weather.select_dtypes(include=['float64', 'int64']).columns

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for numeric columns
Q1 = weather[numeric_cols].quantile(0.25)
Q3 = weather[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

# Define a filter to detect and remove outliers for numeric columns
outlier_filter = ~((weather[numeric_cols] < (Q1 - 1.5 * IQR)) | (weather[numeric_cols] > (Q3 + 1.5 * IQR)))

# Apply filter to remove rows with outliers in numeric columns
weather_no_outliers = weather[outlier_filter.all(axis=1)]

# Display to confirm outliers are removed
weather_no_outliers.shape

(7112, 7)

In [14]:
weather.index = pd.to_datetime(weather.index, format='%Y-%m-%d')
weather.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08',
               '2000-01-09', '2000-01-10',
               ...
               '2024-08-30', '2024-08-31', '2024-09-01', '2024-09-02',
               '2024-09-03', '2024-09-04', '2024-09-05', '2024-09-06',
               '2024-09-07', '2024-09-08'],
              dtype='datetime64[ns]', name='DATE', length=9018, freq=None)

In [15]:
weather.index.year.value_counts().sort_index()

DATE
2000    366
2001    365
2002    365
2003    365
2004    366
2005    365
2006    365
2007    365
2008    366
2009    365
2010    365
2011    365
2012    366
2013    365
2014    365
2015    365
2016    366
2017    365
2018    365
2019    365
2020    366
2021    365
2022    365
2023    365
2024    252
Name: count, dtype: int64

In [17]:
weather

,station,name,awnd,prcp,tavg,tmax,tmin
DATE,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28
...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56

In [37]:
weather["targetmax"] = weather.shift(-1)["tmax"]
weather["targetmin"] = weather.shift(-1)["tmin"]
weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin
DATE,,,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31,54.0,37.0
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37,60.0,46.0
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46,55.0,47.0
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47,47.0,28.0
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28,42.0,23.0
...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,NaN,NaN

In [38]:
weather = weather.ffill()
weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin
DATE,,,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31,54.0,37.0
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37,60.0,46.0
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46,55.0,47.0
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47,47.0,28.0
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28,42.0,23.0
...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0

In [39]:
numeric_weather = weather.select_dtypes(include=[float, int])
correlation_matrix = numeric_weather.corr()
correlation_matrix

,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin
awnd,1.000000,0.100747,-0.172059,-0.260456,-0.258677,-0.311163,-0.316663
prcp,0.100747,1.000000,0.013222,-0.010901,0.052558,-0.002687,0.027070
tavg,-0.172059,0.013222,1.000000,0.685326,0.689606,0.636345,0.656903
tmax,-0.260456,-0.010901,0.685326,1.000000,0.955821,0.916567,0.926585
tmin,-0.258677,0.052558,0.689606,0.955821,1.000000,0.915661,0.950034
targetmax,-0.311163,-0.002687,0.636345,0.916567,0.915661,1.000000,0.955816
targetmin,-0.316663,0.027070,0.656903,0.926585,0.950034,0.955816,1.000000

In [40]:
from sklearn.linear_model import Ridge
rr = Ridge(alpha=.1)

In [41]:
predictors = weather.columns[~weather.columns.isin(["targetmax", "targetmin","name", "station"])]
predictors

Index(['awnd', 'prcp', 'tavg', 'tmax', 'tmin'], dtype='object')

In [46]:
def backtestmax(weather, model, predictors, start = 3650, step =90):
    all_predictions = []

    for i in range(start, weather.shape[0], step):
        train = weather.iloc[:i, :]
        test = weather.iloc[i: (i+step), :]
        
        model.fit(train[predictors], train["targetmax"])
        preds = model.predict(test[predictors])

        preds = pd.Series(preds, index = test.index)
        combined = pd.concat([test["targetmax"], preds], axis = 1)

        combined.columns = ["actual", "prediction"]

        combined["diff"] = (combined["prediction"] - combined["actual"]).abs()

        all_predictions.append(combined)

    return pd.concat(all_predictions)

In [47]:
predictions = backtestmax(weather,rr, predictors)
predictions

            actual  prediction       diff
DATE
2009-12-29    32.0   29.838402   2.161598
2009-12-30    35.0   34.312866   0.687134
2009-12-31    41.0   41.371418   0.371418
2010-01-01    33.0   45.812775  12.812775
2010-01-02    24.0   31.872822   7.872822
...            ...         ...        ...
2024-09-04    78.0   75.035421   2.964579
2024-09-05    79.0   74.955934   4.044066
2024-09-06    75.0   78.305496   3.305496
2024-09-07    74.0   74.313896   0.313896
2024-09-08    74.0   72.098572   1.901428

[5368 rows x 3 columns]

In [48]:
def backtestmin(weather, model, predictors, start = 3650, step =90):
    all_predictions = []

    for i in range(start, weather.shape[0], step):
        train = weather.iloc[:i, :]
        test = weather.iloc[i: (i+step), :]
        
        model.fit(train[predictors], train["targetmin"])
        preds = model.predict(test[predictors])

        preds = pd.Series(preds, index = test.index)
        combined = pd.concat([test["targetmin"], preds], axis = 1)

        combined.columns = ["actual", "prediction"]

        combined["diff"] = (combined["prediction"] - combined["actual"]).abs()

        all_predictions.append(combined)

    return pd.concat(all_predictions)

In [50]:
predictionsmin = backtestmin(weather,rr, predictors)
predictionsmin

            actual  prediction       diff
DATE
2009-12-29    18.0   15.670972   2.329028
2009-12-30    29.0   20.222933   8.777067
2009-12-31    32.0   29.559882   2.440118
2010-01-01    17.0   32.946070  15.946070
2010-01-02    18.0   17.376051   0.623949
...            ...         ...        ...
2024-09-04    57.0   58.804630   1.804630
2024-09-05    63.0   58.482011   4.517989
2024-09-06    60.0   63.059770   3.059770
2024-09-07    56.0   59.532156   3.532156
2024-09-08    56.0   56.433898   0.433898

[5368 rows x 3 columns]

In [51]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(predictions["actual"], predictions["prediction"])

np.float64(5.017992242404582)

In [53]:
def pct_diff(old,new):
    return (new - old)/old

def compute_rolling(weather, horizon, col):
    label = f"rolling_{horizon}_{col}"

    weather[label] = weather[col].rolling(horizon).mean()
    weather[f"{label}_pct"] = pct_diff(weather[label], weather[col])
    return weather

rolling_horizons = [3, 14]

for horizon in rolling_horizons:
    for col in ["tmax", "tmin", "prcp"]:
        weather = compute_rolling(weather, horizon, col)

weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_3_tmin,rolling_3_tmin_pct,rolling_3_prcp,rolling_3_prcp_pct,rolling_14_tmax,rolling_14_tmax_pct,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct
DATE,,,,,,,,,,,,,,,,,,,,,
2000-01-01,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.38,0.00,39.0,46,31,54.0,37.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-02,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,46.0,54,37,60.0,46.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-03,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",3.13,0.00,53.0,60,46,55.0,47.0,53.333333,...,38.000000,0.210526,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.54,0.62,51.0,55,47,47.0,28.0,56.333333,...,43.333333,0.084615,0.206667,2.000000,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",17.67,0.04,38.0,47,28,42.0,23.0,54.000000,...,40.333333,-0.305785,0.220000,-0.818182,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0,78.666667,...,59.333333,-0.039326,0.000000,NaN,81.928571,-0.060157,64.928571,-0.122112,0.022143,-1.000000
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0,77.000000,...,57.000000,0.000000,0.000000,NaN,81.785714,-0.046288,64.642857,-0.118232,0.022143,-1.000000
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0,78.000000,...,59.000000,0.067797,0.000000,NaN,81.500000,-0.030675,64.857143,-0.028634,0.022143,-1.000000
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0,77.333333,...,60.000000,0.000000,0.060000,2.000000,80.857143,-0.072438,64.571429,-0.070796,0.035000,4.142857
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0,76.000000,...,59.666667,-0.061453,0.060000,-1.000000,80.214286,-0.077471,63.785714,-0.122060,0.035000,-1.000000

In [54]:
weather = weather.iloc[14:,:]
weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_3_tmin,rolling_3_tmin_pct,rolling_3_prcp,rolling_3_prcp_pct,rolling_14_tmax,rolling_14_tmax_pct,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct
DATE,,,,,,,,,,,,,,,,,,,,,
2000-01-15,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,24.0,31,16,47.0,22.0,31.333333,...,16.000000,0.000000,0.003333,-1.0,46.000000,-0.326087,32.214286,-0.503326,0.090000,-1.000000
2000-01-16,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",21.25,0.00,35.0,47,22,22.0,8.0,33.666667,...,17.333333,0.269231,0.000000,NaN,45.500000,0.032967,31.142857,-0.293578,0.090000,-1.000000
2000-01-17,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",24.61,0.00,15.0,22,8,19.0,4.0,33.333333,...,15.333333,-0.478261,0.000000,NaN,42.785714,-0.485810,28.428571,-0.718593,0.090000,-1.000000
2000-01-18,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",12.75,0.00,12.0,19,4,30.0,10.0,29.333333,...,11.333333,-0.647059,0.000000,NaN,40.214286,-0.527531,25.357143,-0.842254,0.045714,-1.000000
2000-01-19,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,20.0,30,10,28.0,20.0,23.666667,...,7.333333,0.363636,0.000000,NaN,39.000000,-0.230769,24.071429,-0.584570,0.042857,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0,78.666667,...,59.333333,-0.039326,0.000000,NaN,81.928571,-0.060157,64.928571,-0.122112,0.022143,-1.000000
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0,77.000000,...,57.000000,0.000000,0.000000,NaN,81.785714,-0.046288,64.642857,-0.118232,0.022143,-1.000000
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0,78.000000,...,59.000000,0.067797,0.000000,NaN,81.500000,-0.030675,64.857143,-0.028634,0.022143,-1.000000
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0,77.333333,...,60.000000,0.000000,0.060000,2.0,80.857143,-0.072438,64.571429,-0.070796,0.035000,4.142857
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0,76.000000,...,59.666667,-0.061453,0.060000,-1.0,80.214286,-0.077471,63.785714,-0.122060,0.035000,-1.000000

In [55]:
weather = weather.fillna(0)
weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_3_tmin,rolling_3_tmin_pct,rolling_3_prcp,rolling_3_prcp_pct,rolling_14_tmax,rolling_14_tmax_pct,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct
DATE,,,,,,,,,,,,,,,,,,,,,
2000-01-15,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,24.0,31,16,47.0,22.0,31.333333,...,16.000000,0.000000,0.003333,-1.0,46.000000,-0.326087,32.214286,-0.503326,0.090000,-1.000000
2000-01-16,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",21.25,0.00,35.0,47,22,22.0,8.0,33.666667,...,17.333333,0.269231,0.000000,0.0,45.500000,0.032967,31.142857,-0.293578,0.090000,-1.000000
2000-01-17,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",24.61,0.00,15.0,22,8,19.0,4.0,33.333333,...,15.333333,-0.478261,0.000000,0.0,42.785714,-0.485810,28.428571,-0.718593,0.090000,-1.000000
2000-01-18,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",12.75,0.00,12.0,19,4,30.0,10.0,29.333333,...,11.333333,-0.647059,0.000000,0.0,40.214286,-0.527531,25.357143,-0.842254,0.045714,-1.000000
2000-01-19,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,20.0,30,10,28.0,20.0,23.666667,...,7.333333,0.363636,0.000000,0.0,39.000000,-0.230769,24.071429,-0.584570,0.042857,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0,78.666667,...,59.333333,-0.039326,0.000000,0.0,81.928571,-0.060157,64.928571,-0.122112,0.022143,-1.000000
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0,77.000000,...,57.000000,0.000000,0.000000,0.0,81.785714,-0.046288,64.642857,-0.118232,0.022143,-1.000000
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0,78.000000,...,59.000000,0.067797,0.000000,0.0,81.500000,-0.030675,64.857143,-0.028634,0.022143,-1.000000
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0,77.333333,...,60.000000,0.000000,0.060000,2.0,80.857143,-0.072438,64.571429,-0.070796,0.035000,4.142857
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0,76.000000,...,59.666667,-0.061453,0.060000,-1.0,80.214286,-0.077471,63.785714,-0.122060,0.035000,-1.000000

In [56]:
def expand_mean(df):
    return df.expanding(1).mean()

for col in ["tmax", "tmin", "prcp"]:
    weather[f"month_avg_{col}"] = weather[col].groupby(weather.index.month, group_keys=False).apply(expand_mean)
    weather[f"day_AVG_{col}"] = weather[col].groupby(weather.index.day_of_year, group_keys=False).apply(expand_mean)

weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct,month_avg_tmax,day_AVG_tmax,month_avg_tmin,day_AVG_tmin,month_avg_prcp,day_AVG_prcp
DATE,,,,,,,,,,,,,,,,,,,,,
2000-01-15,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,24.0,31,16,47.0,22.0,31.333333,...,32.214286,-0.503326,0.090000,-1.000000,31.000000,31.00,16.000000,16.00,0.000000,0.0000
2000-01-16,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",21.25,0.00,35.0,47,22,22.0,8.0,33.666667,...,31.142857,-0.293578,0.090000,-1.000000,39.000000,47.00,19.000000,22.00,0.000000,0.0000
2000-01-17,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",24.61,0.00,15.0,22,8,19.0,4.0,33.333333,...,28.428571,-0.718593,0.090000,-1.000000,33.333333,22.00,15.333333,8.00,0.000000,0.0000
2000-01-18,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",12.75,0.00,12.0,19,4,30.0,10.0,29.333333,...,25.357143,-0.842254,0.045714,-1.000000,29.750000,19.00,12.500000,4.00,0.000000,0.0000
2000-01-19,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,20.0,30,10,28.0,20.0,23.666667,...,24.071429,-0.584570,0.042857,-1.000000,29.800000,30.00,12.000000,10.00,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0,78.666667,...,64.928571,-0.122112,0.022143,-1.000000,76.707182,81.16,62.069061,66.48,0.130331,0.0644
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0,77.000000,...,64.642857,-0.118232,0.022143,-1.000000,76.708966,78.40,62.062069,63.16,0.130152,0.1636
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0,78.000000,...,64.857143,-0.028634,0.022143,-1.000000,76.712121,78.72,62.063361,63.64,0.129972,0.1412
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0,77.333333,...,64.571429,-0.070796,0.035000,4.142857,76.709766,80.20,62.060523,64.88,0.130041,0.0264
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0,76.000000,...,63.785714,-0.122060,0.035000,-1.000000,76.706044,78.32,62.052198,64.04,0.129863,0.1644

In [59]:
predictions = backtestmax(weather,rr, predictors)

predictions

            actual  prediction      diff
DATE
2010-01-12    36.0   38.604636  2.604636
2010-01-13    39.0   38.358483  0.641517
2010-01-14    50.0   41.470924  8.529076
2010-01-15    49.0   46.684721  2.315279
2010-01-16    42.0   49.088752  7.088752
...            ...         ...       ...
2024-09-04    78.0   75.033683  2.966317
2024-09-05    79.0   74.955622  4.044378
2024-09-06    75.0   78.305031  3.305031
2024-09-07    74.0   74.315783  0.315783
2024-09-08    74.0   72.100061  1.899939

[5354 rows x 3 columns]

In [60]:
predictionsmin = backtestmin(weather,rr, predictors)
predictionsmin

            actual  prediction      diff
DATE
2010-01-12    24.0   24.832699  0.832699
2010-01-13    25.0   24.854662  0.145338
2010-01-14    27.0   27.308308  0.308308
2010-01-15    33.0   30.009551  2.990449
2010-01-16    31.0   34.308036  3.308036
...            ...         ...       ...
2024-09-04    57.0   58.802155  1.802155
2024-09-05    63.0   58.480620  4.519380
2024-09-06    60.0   63.063969  3.063969
2024-09-07    56.0   59.539136  3.539136
2024-09-08    56.0   56.436636  0.436636

[5354 rows x 3 columns]

In [62]:
mean_absolute_error(predictionsmin["actual"], predictionsmin["prediction"])

np.float64(3.7151475820445037)

In [63]:
predictionsmin.sort_values("diff", ascending = False)

            actual  prediction       diff
DATE
2015-02-22     9.0   33.754958  24.754958
2017-02-08    19.0   42.390877  23.390877
2022-12-22     9.0   31.114385  22.114385
2017-03-09    24.0   45.265688  21.265688
2018-01-12    20.0   41.012594  21.012594
...            ...         ...        ...
2015-03-19    31.0   30.998350   0.001650
2020-08-06    68.0   67.998546   0.001454
2023-07-10    70.0   70.001450   0.001450
2011-10-09    60.0   60.001428   0.001428
2010-07-04    71.0   70.999772   0.000228

[5354 rows x 3 columns]

In [65]:
weather.loc["2015-02-10":"2015-02-28"]

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct,month_avg_tmax,day_AVG_tmax,month_avg_tmin,day_AVG_tmin,month_avg_prcp,day_AVG_prcp
DATE,,,,,,,,,,,,,,,,,,,,,
2015-02-10,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",15.43,0.00,30.0,40,26,35.0,23.0,37.000000,...,19.500000,0.333333,0.100000,-1.000000,41.299539,41.3750,27.398618,26.7500,0.096290,0.109375
2015-02-11,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,30.0,35,23,40.0,18.0,34.666667,...,19.928571,0.154122,0.100000,-1.000000,41.285057,39.0000,27.388506,25.1250,0.096069,0.053750
2015-02-12,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",13.20,0.00,31.0,40,18,23.0,9.0,38.333333,...,20.000000,-0.100000,0.099286,-1.000000,41.282110,38.2500,27.366972,23.8125,0.095849,0.105625
2015-02-13,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",18.79,0.00,19.0,23,9,35.0,16.0,32.666667,...,19.285714,-0.533333,0.096429,-1.000000,41.240275,39.0625,27.324943,25.3125,0.095629,0.167500
2015-02-14,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.51,0.01,24.0,35,16,27.0,5.0,32.666667,...,19.428571,-0.176471,0.097143,-0.897059,41.226027,41.9375,27.299087,27.9375,0.095434,0.120625
2015-02-15,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",27.74,0.01,21.0,27,5,23.0,5.0,28.333333,...,18.285714,-0.726562,0.095714,-0.895522,41.193622,40.8750,27.248292,26.6250,0.095239,0.022500
2015-02-16,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",14.76,0.00,11.0,23,5,27.0,16.0,28.333333,...,17.571429,-0.715447,0.011429,-1.000000,41.152273,38.9375,27.197727,24.8750,0.095023,0.073125
2015-02-17,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",6.93,0.19,20.0,27,16,31.0,15.0,25.666667,...,17.714286,-0.096774,0.025000,6.600000,41.120181,40.1875,27.172336,25.5625,0.095238,0.108125
2015-02-18,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.82,0.00,23.0,31,15,27.0,9.0,27.000000,...,17.214286,-0.128631,0.025000,-1.000000,41.097285,40.5000,27.144796,25.8125,0.095023,0.102500
2015-02-19,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",21.25,0.00,22.0,27,9,21.0,3.0,28.333333,...,16.785714,-0.463830,0.025000,-1.000000,41.065463,40.6875,27.103837,24.4375,0.094808,0.045000
2015-02-20,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",18.79,0.00,11.0,21,3,33.0,11.0,26.333333,...,16.071429,-0.813333,0.025000,-1.000000,41.020270,40.9375,27.049550,27.5000,0.094595,0.011250
2015-02-21,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.59,21.0,33,11,43.0,32.0,27.000000,...,15.071429,-0.270142,0.067143,7.787234,41.002247,43.8125,27.013483,27.8125,0.095708,0.089375
2015-02-22,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",4.03,0.20,34.0,43,32,38.0,9.0,32.333333,...,15.285714,1.093458,0.081429,1.456140,41.006726,42.8750,27.024664,29.5625,0.095942,0.185000
2015-02-23,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",19.01,0.00,29.0,38,9,28.0,7.0,38.000000,...,14.071429,-0.360406,0.071429,-1.000000,41.000000,44.0000,26.984340,29.0625,0.095727,0.133125
2015-02-24,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.40,0.00,13.0,28,7,37.0,19.0,36.333333,...,12.714286,-0.449438,0.071429,-1.000000,40.970982,40.7500,26.939732,27.1250,0.095513,0.076875
2015-02-25,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.74,0.00,28.0,37,19,32.0,23.0,34.333333,...,12.428571,0.528736,0.071429,-1.000000,40.962138,42.5625,26.922049,27.4375,0.095301,0.227500
2015-02-26,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",12.75,0.00,28.0,32,23,32.0,20.0,32.333333,...,12.785714,0.798883,0.071429,-1.000000,40.942222,40.1875,26.913333,28.0625,0.095089,0.081875
2015-02-27,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.29,0.00,25.0,32,20,31.0,15.0,33.666667,...,13.571429,0.473684,0.071429,-1.000000,40.922395,43.3125,26.898004,28.1875,0.094878,0.043125
2015-02-28,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",8.28,0.00,23.0,31,15,33.0,20.0,31.666667,...,13.500000,0.111111,0.070714,-1.000000,40.900442,42.8125,26.871681,28.8125,0.094668,0.041875

In [67]:
predictionsmin["diff"].round().value_counts().sort_index()

diff
0.0      477
1.0     1003
2.0      870
3.0      775
4.0      580
5.0      435
6.0      340
7.0      263
8.0      173
9.0      122
10.0      93
11.0      68
12.0      40
13.0      27
14.0      23
15.0      21
16.0      13
17.0       8
18.0       7
19.0       5
20.0       6
21.0       2
22.0       1
23.0       1
25.0       1
Name: count, dtype: int64

In [68]:
import numpy as np
# Select only numeric columns for feature scaling
numeric_features = weather_no_outliers.select_dtypes(include=[np.number])

# Separate features and target variable
X = numeric_features.drop(columns=['tmax', 'tmin'])  # Drop target columns
y = numeric_features[['tmax', 'tmin']]  # Targets

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes to verify
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5689, 3)
X_test shape: (1423, 3)
y_train shape: (5689, 2)
y_test shape: (1423, 2)

In [69]:
# Check the total number of rows in the dataset after cleaning
print("Total rows in the dataset after cleaning:", weather_no_outliers.shape[0])

Total rows in the dataset after cleaning: 7112

In [70]:
# Import the necessary scaler
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Initialize scalers (we'll try both types)
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# Apply StandardScaler to the features
X_train_scaled_std = standard_scaler.fit_transform(X_train)
X_test_scaled_std = standard_scaler.transform(X_test)

# Apply MinMaxScaler to the features
X_train_scaled_minmax = minmax_scaler.fit_transform(X_train)
X_test_scaled_minmax = minmax_scaler.transform(X_test)

# Check the results
print("Standard Scaled X_train (first 5 rows):\n", X_train_scaled_std[:5])
print("MinMax Scaled X_train (first 5 rows):\n", X_train_scaled_minmax[:5])

Standard Scaled X_train (first 5 rows):
 [[-0.78037521  3.33395686  0.78071021]
 [-0.83906905 -0.36236442  0.78071021]
 [ 0.3534832  -0.36236442  0.9036436 ]
 [-0.18276513  1.22177327  0.78071021]
 [-0.18276513 -0.36236442  0.78071021]]
MinMax Scaled X_train (first 5 rows):
 [[0.34406535 0.7        0.80246914]
 [0.33349351 0.         0.80246914]
 [0.54829409 0.         0.82716049]
 [0.45170591 0.3        0.80246914]
 [0.45170591 0.         0.80246914]]

In [73]:
# Import the Linear Regression model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the model
linear_reg = LinearRegression()

# Train the model on Standard Scaled data
linear_reg.fit(X_train_scaled_std, y_train)

# Make predictions on the test set
y_pred_lr = linear_reg.predict(X_test_scaled_std)

# Evaluate the model
print("Linear Regression - Mean Squared Error:", mean_squared_error(y_test, y_pred_lr))
print("Linear Regression - R^2 Score:", r2_score(y_test, y_pred_lr))

Linear Regression - Mean Squared Error: 140.7638356407537
Linear Regression - R^2 Score: 0.5209940220758515

In [74]:
weather

,station,name,awnd,prcp,tavg,tmax,tmin,targetmax,targetmin,rolling_3_tmax,...,rolling_14_tmin,rolling_14_tmin_pct,rolling_14_prcp,rolling_14_prcp_pct,month_avg_tmax,day_AVG_tmax,month_avg_tmin,day_AVG_tmin,month_avg_prcp,day_AVG_prcp
DATE,,,,,,,,,,,,,,,,,,,,,
2000-01-15,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,24.0,31,16,47.0,22.0,31.333333,...,32.214286,-0.503326,0.090000,-1.000000,31.000000,31.00,16.000000,16.00,0.000000,0.0000
2000-01-16,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",21.25,0.00,35.0,47,22,22.0,8.0,33.666667,...,31.142857,-0.293578,0.090000,-1.000000,39.000000,47.00,19.000000,22.00,0.000000,0.0000
2000-01-17,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",24.61,0.00,15.0,22,8,19.0,4.0,33.333333,...,28.428571,-0.718593,0.090000,-1.000000,33.333333,22.00,15.333333,8.00,0.000000,0.0000
2000-01-18,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",12.75,0.00,12.0,19,4,30.0,10.0,29.333333,...,25.357143,-0.842254,0.045714,-1.000000,29.750000,19.00,12.500000,4.00,0.000000,0.0000
2000-01-19,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",9.84,0.00,20.0,30,10,28.0,20.0,23.666667,...,24.071429,-0.584570,0.042857,-1.000000,29.800000,30.00,12.000000,10.00,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-04,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",5.37,0.00,67.0,77,57,78.0,57.0,78.666667,...,64.928571,-0.122112,0.022143,-1.000000,76.707182,81.16,62.069061,66.48,0.130331,0.0644
2024-09-05,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.61,0.00,68.0,78,57,79.0,63.0,77.000000,...,64.642857,-0.118232,0.022143,-1.000000,76.708966,78.40,62.062069,63.16,0.130152,0.1636
2024-09-06,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",7.83,0.00,69.0,79,63,75.0,60.0,78.000000,...,64.857143,-0.028634,0.022143,-1.000000,76.712121,78.72,62.063361,63.64,0.129972,0.1412
2024-09-07,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.18,70.0,75,60,74.0,56.0,77.333333,...,64.571429,-0.070796,0.035000,4.142857,76.709766,80.20,62.060523,64.88,0.130041,0.0264
2024-09-08,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",10.07,0.00,64.0,74,56,74.0,56.0,76.000000,...,63.785714,-0.122060,0.035000,-1.000000,76.706044,78.32,62.052198,64.04,0.129863,0.1644

In [75]:
# Import the Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

# Initialize the model
rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model on Standard Scaled data
rf_reg.fit(X_train_scaled_std, y_train)

# Make predictions on the test set
y_pred_rf = rf_reg.predict(X_test_scaled_std)

# Evaluate the model
print("Random Forest Regressor - Mean Squared Error:", mean_squared_error(y_test, y_pred_rf))
print("Random Forest Regressor - R^2 Score:", r2_score(y_test, y_pred_rf))

Random Forest Regressor - Mean Squared Error: 97.50205926513874
Random Forest Regressor - R^2 Score: 0.6682762012846237